### ISSUE TITLE
Dataset Citation

### ISSUE THREAD

**Issue by daniyyell-dev** [ExtraHop/DGA-Detection-Training-Dataset#1]
Hello guys, First of all thank you for making the dataset public, I'm working on this dataset for my academic project and I'm pretty excited about it. I'm curious about how to cite the dataset – do you have a preferred method?

**Comment by tkemmerling** [comment]
Hi, sorry it took me a little time to get back to you. Based on our license you are not required to cite the dataset but we would appreciate you doing so. I think providing a short description of the dataset, and the link to the repo would be great. I would also be very interested in knowing how you are using the dataset, and what value it has to you? 

Regards Todd K.

**Comment by daniyyell-dev** [comment]
Hello Todd,

I appreciate your prompt response to my earlier query. In addition to my previous message, I would like to inquire if it's feasible to determine the number of DGA attack families within the dataset. If not, could you please provide explicit details on how the dataset was compiled? All descriptions can be on GitHub, which would be immensely helpful.

Regarding your question about using the dataset, I want to emphasise its significance. This dataset holds excellent value as it offers unprecedented insights not available in previous studies, and I will be happy to share the research with you.

Thank you.
- Daniel

**Comment by tkemmerling** [comment]
The number of dga algorithims in the data is at least 43. Here is a link to an article and several repos where you can find what is now a superset of these algorithms.  There are approximately 300K dgas where the algorithm used to generate them is unknown. The non dga part of the dataset was curated from domains that remained 'stable' over time. TK

https://jason-trost.medium.com/getting-started-with-dga-domain-detection-research-89af69213257

**Comment by daniyyell-dev** [comment]
Hello Todd, The information you have provided is more than enough. Thank you for your time. Best regards, Daniel
